import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { config } from "../config";
import { StoredDataset } from "../types";

/**
 * Two distinct caches living in this one module, because they solve different
 * problems and have different lifecycles:
 *
 * 1. HTTP response cache (`httpCache`) -- prevents redundant network calls to
 *    Wikidata/Wikimedia when an agent loop re-resolves the same topic or
 *    re-analyzes the same articles across several turns. In-memory + TTL is
 *    enough here (per the task's "in-memory or SQLite" allowance): the data is
 *    small, cheap to refetch on process restart, and a TTL protects against ever
 *    serving genuinely stale "today" pageview counts (which do get revised).
 *
 * 2. Dataset store (`datasetStore`) -- holds the FULL daily time series behind
 *    the opaque `dataset_id` handed to the LLM. This must survive being read
 *    back by a *later* tool call (generate chart, generate PDF) potentially
 *    several turns later, so it's persisted to disk as JSON rather than kept
 *    only in memory.
 */

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

// ---------------------------------------------------------------------------
// 1. In-memory HTTP cache with TTL
// ---------------------------------------------------------------------------

interface CacheEntry<T> {
  value: T;
  expiresAt: number;
}

const httpCache = new Map<string, CacheEntry<unknown>>();

export function cacheKeyFor(url: string, params?: Record<string, unknown>): string {
  const paramString = params ? JSON.stringify(params, Object.keys(params).sort()) : "";
  return crypto.createHash("sha1").update(url + paramString).digest("hex");
}

export async function withHttpCache<T>(key: string, fetcher: () => Promise<T>): Promise<T> {
  const cached = httpCache.get(key);
  if (cached && cached.expiresAt > Date.now()) {
    return cached.value as T;
  }

  const value = await fetcher();
  httpCache.set(key, { value, expiresAt: Date.now() + config.httpCacheTtlMs });
  return value;
}

// ---------------------------------------------------------------------------
// 2. Persisted dataset store
// ---------------------------------------------------------------------------

function datasetPath(datasetId: string): string {
  // datasetId is generated by us (uuid), never user input, so no path traversal risk.
  return path.join(config.datasetsDir, `${datasetId}.json`);
}

export function saveDataset(dataset: StoredDataset): void {
  ensureDir(config.datasetsDir);
  fs.writeFileSync(datasetPath(dataset.datasetId), JSON.stringify(dataset), "utf-8");
}

export function loadDataset(datasetId: string): StoredDataset | null {
  const file = datasetPath(datasetId);
  if (!fs.existsSync(file)) return null;
  const raw = fs.readFileSync(file, "utf-8");
  return JSON.parse(raw) as StoredDataset;
}
