import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { config } from "../config";
import { StoredDataset } from "../types";

/**
 * Two distinct caches living in this one module, because they solve different
 * problems and have different lifecycles:
 *
 * 1. HTTP response cache (`httpCache`) -- prevents redundant network calls to
 *    Wikidata/Wikimedia when the same topic/article is re-resolved or
 *    re-analyzed across several turns. This MUST be disk-backed, not purely
 *    in-memory: the CLI (`dist/cli.js`), which is this skill's primary
 *    integration path (see SKILL.md), invokes a fresh `node` process per tool
 *    call -- an in-memory-only cache would be created and discarded on every
 *    single call and would never actually deduplicate anything there. A small
 *    in-memory layer is kept on top purely to avoid re-reading the same file
 *    twice within one process (e.g. the native tool-calling harnesses, which
 *    do stay alive for a whole conversation).
 *
 * 2. Dataset store (`datasetStore`) -- holds the FULL daily time series behind
 *    the opaque `dataset_id` handed to the LLM. This must survive being read
 *    back by a *later* tool call (generate chart, generate PDF) potentially
 *    several turns later, so it's persisted to disk as JSON rather than kept
 *    only in memory.
 */

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

// ---------------------------------------------------------------------------
// 1. Disk-backed HTTP cache with TTL (+ in-memory layer for same-process hits)
// ---------------------------------------------------------------------------

interface CacheEntry<T> {
  value: T;
  expiresAt: number;
}

const httpCache = new Map<string, CacheEntry<unknown>>();

export function cacheKeyFor(url: string, params?: Record<string, unknown>): string {
  const paramString = params ? JSON.stringify(params, Object.keys(params).sort()) : "";
  return crypto.createHash("sha1").update(url + paramString).digest("hex");
}

function httpCachePath(key: string): string {
  return path.join(config.cacheDir, `${key}.json`);
}

function readDiskCache<T>(key: string): CacheEntry<T> | null {
  try {
    const raw = fs.readFileSync(httpCachePath(key), "utf-8");
    return JSON.parse(raw) as CacheEntry<T>;
  } catch {
    return null; // missing/corrupt cache file is just a cache miss, never a hard error
  }
}

function writeDiskCache<T>(key: string, entry: CacheEntry<T>): void {
  ensureDir(config.cacheDir);
  fs.writeFileSync(httpCachePath(key), JSON.stringify(entry), "utf-8");
}

export async function withHttpCache<T>(key: string, fetcher: () => Promise<T>): Promise<T> {
  const now = Date.now();

  const inMemory = httpCache.get(key);
  if (inMemory && inMemory.expiresAt > now) {
    return inMemory.value as T;
  }

  const onDisk = readDiskCache<T>(key);
  if (onDisk && onDisk.expiresAt > now) {
    httpCache.set(key, onDisk);
    return onDisk.value;
  }

  const value = await fetcher();
  const entry: CacheEntry<T> = { value, expiresAt: now + config.httpCacheTtlMs };
  httpCache.set(key, entry);
  writeDiskCache(key, entry);
  return value;
}

// ---------------------------------------------------------------------------
// 2. Persisted dataset store
// ---------------------------------------------------------------------------

function datasetPath(datasetId: string): string {
  // datasetId is generated by us (uuid), never user input, so no path traversal risk.
  return path.join(config.datasetsDir, `${datasetId}.json`);
}

export function saveDataset(dataset: StoredDataset): void {
  ensureDir(config.datasetsDir);
  fs.writeFileSync(datasetPath(dataset.datasetId), JSON.stringify(dataset), "utf-8");
}

export function loadDataset(datasetId: string): StoredDataset | null {
  const file = datasetPath(datasetId);
  if (!fs.existsSync(file)) return null;
  const raw = fs.readFileSync(file, "utf-8");
  return JSON.parse(raw) as StoredDataset;
}
